version: "2.2"

services:
  cassandra-cl1:
    container_name: cassandra-cl1
    image: cassandra
    ports: 
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Restaurants
    volumes:
    - ./restaurants.csv:/restaurants.csv
    - ./restaurants_inspections.csv:/restaurants_inspections.csv
      
  cassandra-cl2:
    container_name: cassandra-cl2
    image: cassandra
    ports: 
      - 9043:9042
    command: /bin/bash -c "sleep 30 && echo ' --Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    links:
      - cassandra-cl1:seed
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_CLUSTER_NAME=Restaurants
    volumes:
    - /cassandra_resto:/restaurants.csv
    - /cassandra_resto:/restaurants_inspections.csv
    - /cassandra_resto:/docker-entrypoint-initdb.d